### ISSUE TITLE
Make it possible to save checkpoints for different models in same repo

### ISSUE THREAD

**Issue by elias-sundqvist** [elias-sundqvist/DATX02-20-04#22]
Right now it seems like the checkpoint gets saved directly to the ckpts folder  regardless of which model is being trained. This means that if you train model A and save the checpoint, then try to train model B, it will fail because the saved weights are not valid for model B. 

Each model should have its own checkpoint folder.

**Comment by chrarvi** [comment]
Aren't checkpoint paths defined in hyperparameters under `save_dir`?
I thought it created a ckpt folder in the save_dir folder which by default is `./`.

I could add a flag for it but I'd first like to split this into its own files
