### ISSUE TITLE
Make script to simplify remote training

### ISSUE THREAD

**Issue by elias-sundqvist** [elias-sundqvist/DATX02-20-04#23]
It would be very nice if we could have a script that started remote training for us. 

To train the gan example for example I would just like to write.

train-remote gan_example.py --branch spec-gan-branch --pass ******
or something along those lines.

**Comment by Kyuuhachi** [comment]
I made something, feel free to check it out

**Comment by chrarvi** [comment]
I'd recommend you make a pull request next time! It's just so that it's easier for us to review the code and gather it all under one issue/PR.

That said, I saw you stored the IP in the code. We should store that separately and also clean the repo of that commit.

**Comment by Kyuuhachi** [comment]
Yeah, good points. I'm not very used to using multi-person repos, but I really should have thought to scrub the IP before committing.
